dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decideprueba password 'complexpassword'"
- psql -U postgres -c "create database decideprueba owner decideprueba"
- psql -U postgres -c "ALTER USER decideprueba CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install django-chartjs
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- ./manage.py makemigrations
- ./manage.py migrate
- ./manage.py test --keepdb
#deploy:
#  provider: heroku
#  app: decide-part-zumeta
#  strategy: git
#  api_key: $HEROKU_TOKEN
#  on:
#    branch: develop
